import { DIAGONAL_MOVEMENT_FACTOR } from "@root/domains/space/constants/movement.constants";

export const PLAYER_MOVING_SPEED_PER_SECOND = 8;
export const PLAYER_DIAGONAL_MOVING_SPEED_PER_SECOND = PLAYER_MOVING_SPEED_PER_SECOND * DIAGONAL_MOVEMENT_FACTOR;