export const DIAGONAL_MOVEMENT_FACTOR = Math.sqrt(1 / 2)
export const PLAYER_MOVING_SPEED_PER_SECOND = 8
export const PLAYER_DIAGONAL_MOVING_SPEED_PER_SECOND = PLAYER_MOVING_SPEED_PER_SECOND * DIAGONAL_MOVEMENT_FACTOR
export const CANVAS_WIDTH = 800
export const CANVAS_HEIGHT = 700
